/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Allclass.Basic_data;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author Youtech BD
 */
public class Generel_Part extends javax.swing.JFrame {

    /**
     * Creates new form Generel_Part
     */
    public Generel_Part() {
        initComponents();
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Fa_name = new javax.swing.JTextField();
        Ma_name = new javax.swing.JTextField();
        Add1 = new javax.swing.JTextField();
        Add2 = new javax.swing.JTextField();
        Mob = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Sex = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Nationality = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Dob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generel Part");
        setMinimumSize(new java.awt.Dimension(613, 485));
        setPreferredSize(new java.awt.Dimension(613, 447));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 64, 80, 34));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Father's Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 110, 97, 28));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mother's Name:");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 156, 97, -1));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Present Address:");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 202, 105, -1));

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Permanent Address:");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 248, 128, -1));

        jLabel6.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Number:");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 294, 111, -1));

        Name.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Name.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 64, 224, -1));

        Fa_name.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Fa_name.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Fa_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 224, -1));

        Ma_name.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Ma_name.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Ma_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 156, 224, -1));

        Add1.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Add1.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 202, 379, -1));

        Add2.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Add2.setMinimumSize(new java.awt.Dimension(80, 34));
        Add2.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 248, 379, -1));

        Mob.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Mob.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 294, 127, -1));

        jButton1.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sex:");
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 346, -1, -1));

        Sex.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Sex.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 346, 127, -1));

        jLabel8.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nationality:");
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 346, -1, -1));

        Nationality.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Nationality.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 346, 120, -1));

        jLabel10.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date Of Birth:");
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 294, 86, -1));

        Dob.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        Dob.setPreferredSize(new java.awt.Dimension(80, 34));
        getContentPane().add(Dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 294, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BASIC INFO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/77833_680x550.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setPreferredSize(new java.awt.Dimension(5, 5));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   
     
    JTextField[] textFields = {Name, Fa_name,Ma_name,Add1,Add2,Mob,Sex,Nationality,Dob};
    Basic_data n1 = new Basic_data();
    n1.set(textFields);
    Educational_Part one=new Educational_Part();
    one.setVisible(true);
    setVisible(false); 
        
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generel_Part.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generel_Part.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generel_Part.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generel_Part.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generel_Part().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add1;
    private javax.swing.JTextField Add2;
    private javax.swing.JTextField Dob;
    private javax.swing.JTextField Fa_name;
    private javax.swing.JTextField Ma_name;
    private javax.swing.JTextField Mob;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Nationality;
    private javax.swing.JTextField Sex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public Object getBtnNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
